USE NOTA_FISCAL_NORMALIZADA;

-- forma classica de consultas combinadas
SELECT NOTA_FISCAL.*, ITEM_NOTA_FISCAL.*
FROM NOTA_FISCAL, ITEM_NOTA_FISCAL 
WHERE NOTA_FISCAL.NRO_NOTA = ITEM_NOTA_FISCAL.NRO_NOTA;

-- podemos definir ALIAS (apelidos) para as tabelas e facilitar a codificaçãoptimize
SELECT NF.*, INF.*
FROM NOTA_FISCAL AS NF, ITEM_NOTA_FISCAL AS INF
WHERE NF.NRO_NOTA = INF.NRO_NOTA;

-- um pouco mais mais facilitada e preciso / forcando pela tabela mestra
SELECT NF.NRO_NOTA, NF.DT_EMISSAO, NF.VL_TOTAL,  
		INF.COD_PRODUTO, P.DESC_PRODUTO, P.UN_MED, 
        INF.QTD_PRODUTO, INF.VL_PRECO, INF.VL_TOTAL
FROM 
	NOTA_FISCAL AS NF, 
    ITEM_NOTA_FISCAL AS INF,
    PRODUTO AS P
WHERE NF.NRO_NOTA = INF.NRO_NOTA
	AND INF.COD_PRODUTO = P.COD_PRODUTO
ORDER BY NF.NRO_NOTA DESC, INF.COD_PRODUTO ASC;

-- inner join: intersecção (tirada a clasula where e a consulta feita no from. e o where vai ser utilizado para especificar)
SELECT NF.NRO_NOTA, NF.DT_EMISSAO, NF.VL_TOTAL,  
		INF.COD_PRODUTO, P.DESC_PRODUTO, P.UN_MED, 
        INF.QTD_PRODUTO, INF.VL_PRECO, INF.VL_TOTAL
FROM 
	NOTA_FISCAL AS NF 
    INNER JOIN 
		ITEM_NOTA_FISCAL AS INF ON NF.NRO_NOTA = INF.COD_PRODUTO
    INNER JOIN 
		PRODUTO AS P ON  INF.COD_PRODUTO = P.COD_PRODUTO
WHERE NF.NRO_NOTA = 2
ORDER BY NF.NRO_NOTA DESC, INF.COD_PRODUTO ASC;

-- funções de agregação
-- contando e quantificando registro
-- quantas nota ficais tem emitidas
SELECT COUNT(*) FROM NOTA_FISCAL;

-- notas ficais por periodo
SELECT COUNT(*) FROM NOTA_FISCAL WHERE DT_EMISSAO > '2025-03-21' AND DT_EMISSAO < '2025-03-25';
SELECT COUNT(*) FROM NOTA_FISCAL WHERE DT_EMISSAO BETWEEN '2025-03-21' AND '2025-03-25'; -- menor sempre antes

-- total de notas no ano
SELECT COUNT(*) FROM NOTA_FISCAL WHERE YEAR (DT_EMISSAO) = 2025;

--  max() obtendo o cliente que mais comprou determinado produto em uma unica NF
SELECT NF.NM_CLIENTE AS CLIENTE, P.DESC_PRODUTO AS PRODUTO, MAX(QTD_PRODUTO) AS QTD
FROM ITEM_NOTA_FISCAL AS INF
	INNER JOIN NOTA_FISCAL AS NF 
		ON INF.NRO_NOTA = NF.NRO_NOTA
	INNER JOIN PRODUTO AS P
		ON INF.COD_PRODUTO = P.COD_PRODUTO
-- WHERE INF.COD_PRODUTO = 2
	GROUP BY NF.NM_CLIENTE, P.DESC_PRODUTO
ORDER BY CLIENTE, QTD DESC;
