CREATE DATABASE UNOESC_BACK;
USE UNOESC_BACK;
CREATE TABLE CLIENTE(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR (255)
);

create TABLE CONTA (
	ID INT NOT NULL auto_increment primary key,
    NRO_CONTA VARCHAR(10) NOT NULL,
    ID_CLIENTE INT NOT NULL,
    CONSTRAINT FK_ID_CLIENTE_CONTA
		foreign key (ID_CLIENTE)
        references CLIENTE(ID)
);

CREATE table TRASACAO (
	ID INT not NULL auto_increment PRIMARY KEY,
    ID_CONTA INT NOT NULL,
    TIPO_TRASACAO INT NOT NULL,
    DATA_HORA DATETIME NOT NULL,
	VALOR FLOAT NOT NULL
);
-- DEFININDO CHAVE ESTRANGERIA APOS A CRIAÇÃO DA TABELA
ALTER TABLE TRASACAO 
add foreign key(ID_CONTA)
references CONTA(ID);

CREATE INDEX IDX_TRANSACAO_TO_TRASACAO
ON TRASACAO (TIPO_TRASACAO);

CREATE INDEX IDX_TRANSACAO_DATA_HORA
ON TRASACAO (DATA_HORA);

