CREATE DATABASE NOTA_FISCAL_NORMALIZADA;
USE NOTA_FISCAL_NORMALIZADA;

CREATE TABLE `NOTA_FISCAL`(
    `NRO_NOTA` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `NM_CLIENTE` VARCHAR(256) NOT NULL,
    `END_CLIENTE` VARCHAR (256) NOT NULL,
    `NM_VENDEDOR` VARCHAR (256) NOT NULL,
    `DT_EMISSAO` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `VL_TOTAL` FLOAT NOT NULL
);

CREATE TABLE `PRODUTO`(
    `COD_PRODUTO` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `DESC_PRODUTO` VARCHAR (256) NOT NULL,
    `UN_MED` CHAR(2) NOT NULL,
    `VL_PRODUTO` FLOAT NOT NULL
);

CREATE TABLE `ITEM_NOTA_FISCAL`(
    `NRO_NOTA` INT NOT NULL,
    `COD_PRODUTO` INT NOT NULL,
    `QTD_PRODUTO` INT NOT NULL,
    `VL_PRECO` FLOAT NOT NULL,
    `VL_TOTAL` FLOAT NOT NULL,
    PRIMARY KEY(NRO_NOTA, COD_PRODUTO),
    CONSTRAINT FK_NRO_NOTA_FISCAL 
        FOREIGN KEY (NRO_NOTA) REFERENCES NOTA_FISCAL (NRO_NOTA),
    CONSTRAINT FK_COD_PRODUTO
        FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO (COD_PRODUTO)
);


INSERT INTO `PRODUTO` (DESC_PRODUTO, UN_MED, VL_PRODUTO)
VALUES ('LEITE', 'LT', 4.50);
INSERT INTO `PRODUTO` (DESC_PRODUTO, UN_MED, VL_PRODUTO)
VALUES ('DESODORANTE', 'UN', 8);
INSERT INTO `PRODUTO` (DESC_PRODUTO, UN_MED, VL_PRODUTO)
VALUES ('SALAME', 'KG', 40);
INSERT INTO `PRODUTO` (DESC_PRODUTO, UN_MED, VL_PRODUTO)
VALUES ('BOLA', 'KG', 1);

INSERT INTO `NOTA_FISCAL` (NM_CLIENTE, END_CLIENTE, NM_VENDEDOR, VL_TOTAL)
VALUES ('CHRISTOPHER', 'SIDNEY', 'FELIX', 4500);
INSERT INTO `NOTA_FISCAL` (NM_CLIENTE, END_CLIENTE, NM_VENDEDOR, VL_TOTAL)
VALUES ('JENO', 'SEOUL', 'JAEMIN', 1500);
INSERT INTO `NOTA_FISCAL` (NM_CLIENTE, END_CLIENTE, NM_VENDEDOR, VL_TOTAL)
VALUES ('MARK', 'TORONTO', 'FELIX', 4500);

INSERT INTO ITEM_NOTA_FISCAL (`NRO_NOTA`, `COD_PRODUTO`, `QTD_PRODUTO`, `VL_PRECO`, `VL_TOTAL`)
VALUES (1, 2, 2, 55, 65);
INSERT INTO ITEM_NOTA_FISCAL (`NRO_NOTA`, `COD_PRODUTO`, `QTD_PRODUTO`, `VL_PRECO`, `VL_TOTAL`)
VALUES (3, 2, 1, 85, 45);
INSERT INTO ITEM_NOTA_FISCAL (`NRO_NOTA`, `COD_PRODUTO`, `QTD_PRODUTO`, `VL_PRECO`, `VL_TOTAL`)
VALUES (3, 1, 3, 85.4, 74.5);
INSERT INTO ITEM_NOTA_FISCAL (`NRO_NOTA`, `COD_PRODUTO`, `QTD_PRODUTO`, `VL_PRECO`, `VL_TOTAL`)
VALUES (2, 1, 2, 51.2, 43.5);
INSERT INTO ITEM_NOTA_FISCAL (`NRO_NOTA`, `COD_PRODUTO`, `QTD_PRODUTO`, `VL_PRECO`, `VL_TOTAL`)
VALUES (2, 2, 2, 73, 27);
INSERT INTO ITEM_NOTA_FISCAL (`NRO_NOTA`, `COD_PRODUTO`, `QTD_PRODUTO`, `VL_PRECO`, `VL_TOTAL`)
VALUES (2, 3, 2, 83, 149);

SELECT * FROM PRODUTO;

UPDATE PRODUTO SET VL_PRODUTO = 50, DESC_PRODUTO = 'ATUALIZADO', UN_MED = 'CX'
WHERE COD_PRODUTO = 3;
-- neste caso uma excecao será lançada que amarra o produto ao item da nita fiscal
-- não é possivel excluir uma chave primaria que tem depencias de chave estrangeiras
DELETE FROM PRODUTO WHERE COD_PRODUTO = 3;

INSERT INTO `PRODUTO` (DESC_PRODUTO, UN_MED, VL_PRODUTO)
VALUES ('TESTES DELETE', 'LT', 127);
DELETE FROM PRODUTO WHERE COD_PRODUTO = 5;
